load("@rules_jvm_external//private/rules:jvm_import.bzl", "jvm_import")

jvm_import(
  name = "protos",
  jars = ["android-protos-kt-1.1.2231.jar"],
  srcjar = "android-protos-kt-1.1.2231-sources.jar",
)